In [94]:
import pandas as pd
import numpy as np

In [95]:
df=pd.read_csv('customer_churn_dataset.csv')

In [96]:
df.head()

CustomerID   Age  Gender  Tenure  Usage Frequency  Support Calls  \
0         2.0  30.0  Female    39.0             14.0            5.0   
1         3.0  65.0  Female    49.0              1.0           10.0   
2         4.0  55.0  Female    14.0              4.0            6.0   
3         5.0  58.0    Male    38.0             21.0            7.0   
4         6.0  23.0    Male    32.0             20.0            5.0   

   Payment Delay Subscription Type Contract Length  Total Spend  \
0           18.0          Standard          Annual        932.0   
1            8.0             Basic         Monthly        557.0   
2           18.0             Basic       Quarterly        185.0   
3            7.0          Standard         Monthly        396.0   
4            8.0             Basic         Monthly        617.0   

   Last Interaction  Churn  
0              17.0    1.0  
1               6.0    1.0  
2               3.0    1.0  
3              29.0    1.0  
4              20.0    1.0

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 440833 entries, 0 to 440832
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype  
---  ------             --------------   -----  
 0   CustomerID         440832 non-null  float64
 1   Age                440832 non-null  float64
 2   Gender             440832 non-null  object 
 3   Tenure             440832 non-null  float64
 4   Usage Frequency    440832 non-null  float64
 5   Support Calls      440832 non-null  float64
 6   Payment Delay      440832 non-null  float64
 7   Subscription Type  440832 non-null  object 
 8   Contract Length    440832 non-null  object 
 9   Total Spend        440832 non-null  float64
 10  Last Interaction   440832 non-null  float64
 11  Churn              440832 non-null  float64
dtypes: float64(9), object(3)
memory usage: 40.4+ MB


In [98]:
#eda

df.isnull().sum()

CustomerID           1
Age                  1
Gender               1
Tenure               1
Usage Frequency      1
Support Calls        1
Payment Delay        1
Subscription Type    1
Contract Length      1
Total Spend          1
Last Interaction     1
Churn                1
dtype: int64

In [99]:
df.dropna(inplace=True)

In [100]:
df.isnull().sum()

CustomerID           0
Age                  0
Gender               0
Tenure               0
Usage Frequency      0
Support Calls        0
Payment Delay        0
Subscription Type    0
Contract Length      0
Total Spend          0
Last Interaction     0
Churn                0
dtype: int64

In [101]:
from sklearn.preprocessing import OneHotEncoder,LabelEncoder

In [102]:
df.head()

CustomerID   Age  Gender  Tenure  Usage Frequency  Support Calls  \
0         2.0  30.0  Female    39.0             14.0            5.0   
1         3.0  65.0  Female    49.0              1.0           10.0   
2         4.0  55.0  Female    14.0              4.0            6.0   
3         5.0  58.0    Male    38.0             21.0            7.0   
4         6.0  23.0    Male    32.0             20.0            5.0   

   Payment Delay Subscription Type Contract Length  Total Spend  \
0           18.0          Standard          Annual        932.0   
1            8.0             Basic         Monthly        557.0   
2           18.0             Basic       Quarterly        185.0   
3            7.0          Standard         Monthly        396.0   
4            8.0             Basic         Monthly        617.0   

   Last Interaction  Churn  
0              17.0    1.0  
1               6.0    1.0  
2               3.0    1.0  
3              29.0    1.0  
4              20.0    1.0

In [103]:
le=LabelEncoder()
gender=le.fit_transform(df['Gender'])

df['Gender']=gender

In [104]:
ohe=OneHotEncoder(sparse_output=False)


contract_length=ohe.fit_transform(df[['Contract Length']])

contract_length=pd.DataFrame(contract_length,columns=ohe.get_feature_names_out())

df=pd.concat([df,contract_length],axis=1)


In [105]:
df.head()

CustomerID   Age  Gender  Tenure  Usage Frequency  Support Calls  \
0         2.0  30.0     0.0    39.0             14.0            5.0   
1         3.0  65.0     0.0    49.0              1.0           10.0   
2         4.0  55.0     0.0    14.0              4.0            6.0   
3         5.0  58.0     1.0    38.0             21.0            7.0   
4         6.0  23.0     1.0    32.0             20.0            5.0   

   Payment Delay Subscription Type Contract Length  Total Spend  \
0           18.0          Standard          Annual        932.0   
1            8.0             Basic         Monthly        557.0   
2           18.0             Basic       Quarterly        185.0   
3            7.0          Standard         Monthly        396.0   
4            8.0             Basic         Monthly        617.0   

   Last Interaction  Churn  Contract Length_Annual  Contract Length_Monthly  \
0              17.0    1.0                     1.0                      0.0   
1               6.0    1.0                     0.0                      1.0   
2               3.0    1.0                     0.0                      0.0   
3              29.0    1.0                     0.0                      1.0   
4              20.0    1.0                     0.0                      1.0   

   Contract Length_Quarterly  
0                        0.0  
1                        0.0  
2                        1.0  
3                        0.0  
4                        0.0

In [106]:
df.isna().sum()

CustomerID                   1
Age                          1
Gender                       1
Tenure                       1
Usage Frequency              1
Support Calls                1
Payment Delay                1
Subscription Type            1
Contract Length              1
Total Spend                  1
Last Interaction             1
Churn                        1
Contract Length_Annual       1
Contract Length_Monthly      1
Contract Length_Quarterly    1
dtype: int64

In [107]:
df.dropna(inplace=True)

In [108]:
print(df['Subscription Type'].unique())

['Standard' 'Basic' 'Premium']


In [109]:
subscription=ohe.fit_transform(df[['Subscription Type']])

subscription=pd.DataFrame(subscription,columns=ohe.get_feature_names_out())

df=pd.concat([df,subscription],axis=1)

In [110]:
df.head()

CustomerID   Age  Gender  Tenure  Usage Frequency  Support Calls  \
0         2.0  30.0     0.0    39.0             14.0            5.0   
1         3.0  65.0     0.0    49.0              1.0           10.0   
2         4.0  55.0     0.0    14.0              4.0            6.0   
3         5.0  58.0     1.0    38.0             21.0            7.0   
4         6.0  23.0     1.0    32.0             20.0            5.0   

   Payment Delay Subscription Type Contract Length  Total Spend  \
0           18.0          Standard          Annual        932.0   
1            8.0             Basic         Monthly        557.0   
2           18.0             Basic       Quarterly        185.0   
3            7.0          Standard         Monthly        396.0   
4            8.0             Basic         Monthly        617.0   

   Last Interaction  Churn  Contract Length_Annual  Contract Length_Monthly  \
0              17.0    1.0                     1.0                      0.0   
1               6.0    1.0                     0.0                      1.0   
2               3.0    1.0                     0.0                      0.0   
3              29.0    1.0                     0.0                      1.0   
4              20.0    1.0                     0.0                      1.0   

   Contract Length_Quarterly  Subscription Type_Basic  \
0                        0.0                      0.0   
1                        0.0                      1.0   
2                        1.0                      1.0   
3                        0.0                      0.0   
4                        0.0                      1.0   

   Subscription Type_Premium  Subscription Type_Standard  
0                        0.0                         1.0  
1                        0.0                         0.0  
2                        0.0                         0.0  
3                        0.0                         1.0  
4                        0.0                         0.0

In [111]:
new_df=df.drop(columns=['Contract Length','Subscription Type'])

In [112]:

new_df.head()

CustomerID   Age  Gender  Tenure  Usage Frequency  Support Calls  \
0         2.0  30.0     0.0    39.0             14.0            5.0   
1         3.0  65.0     0.0    49.0              1.0           10.0   
2         4.0  55.0     0.0    14.0              4.0            6.0   
3         5.0  58.0     1.0    38.0             21.0            7.0   
4         6.0  23.0     1.0    32.0             20.0            5.0   

   Payment Delay  Total Spend  Last Interaction  Churn  \
0           18.0        932.0              17.0    1.0   
1            8.0        557.0               6.0    1.0   
2           18.0        185.0               3.0    1.0   
3            7.0        396.0              29.0    1.0   
4            8.0        617.0              20.0    1.0   

   Contract Length_Annual  Contract Length_Monthly  Contract Length_Quarterly  \
0                     1.0                      0.0                        0.0   
1                     0.0                      1.0                        0.0   
2                     0.0                      0.0                        1.0   
3                     0.0                      1.0                        0.0   
4                     0.0                      1.0                        0.0   

   Subscription Type_Basic  Subscription Type_Premium  \
0                      0.0                        0.0   
1                      1.0                        0.0   
2                      1.0                        0.0   
3                      0.0                        0.0   
4                      1.0                        0.0   

   Subscription Type_Standard  
0                         1.0  
1                         0.0  
2                         0.0  
3                         1.0  
4                         0.0

In [113]:
new_df['Churn'].value_counts()

Churn
1.0    249999
0.0    190832
Name: count, dtype: int64

In [114]:
new_df.corr()['Churn'].sort_values(ascending=False)

Churn                         1.000000
Support Calls                 0.574266
Contract Length_Monthly       0.433308
Payment Delay                 0.312130
Age                           0.218393
Last Interaction              0.149618
Subscription Type_Basic       0.020479
Subscription Type_Standard   -0.009241
Subscription Type_Premium    -0.011032
Usage Frequency              -0.046100
Tenure                       -0.051917
Gender                       -0.175393
Contract Length_Annual       -0.175837
Contract Length_Quarterly    -0.176172
Total Spend                  -0.429356
CustomerID                   -0.839365
Name: Churn, dtype: float64

In [115]:
new_df.dropna(inplace=True)

In [116]:
new_df['Churn'].astype(int)

0         1
1         1
2         1
3         1
4         1
         ..
440826    0
440827    0
440828    0
440829    0
440830    0
Name: Churn, Length: 440830, dtype: int64

In [117]:
df['Churn'].dropna(inplace=True)

In [118]:
X=new_df.drop(columns=['Churn','CustomerID'])
y=new_df['Churn']

In [119]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=25)

In [120]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()
rfc.fit(X_train,y_train)
y_train_pred=rfc.predict(X_train)
y_test_pred=rfc.predict(X_test)


In [121]:
from sklearn.metrics import roc_auc_score
#random forest
roc_score={}
probs=rfc.predict_proba(X_test)[:,1]
roc_score['random_forest']=roc_auc_score(y_test,probs)




In [122]:
from sklearn.metrics import classification_report , confusion_matrix

report=classification_report(y_train,y_train_pred)
matrix=confusion_matrix(y_train,y_train_pred)
print(report)
print(matrix)


report=classification_report(y_test,y_test_pred)
matrix=confusion_matrix(y_test,y_test_pred)
print(report)
print(matrix)

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00    152568
         1.0       1.00      1.00      1.00    200096

    accuracy                           1.00    352664
   macro avg       1.00      1.00      1.00    352664
weighted avg       1.00      1.00      1.00    352664

[[152568      0]
 [     3 200093]]
              precision    recall  f1-score   support

         0.0       0.99      1.00      1.00     38263
         1.0       1.00      0.99      1.00     49903

    accuracy                           1.00     88166
   macro avg       1.00      1.00      1.00     88166
weighted avg       1.00      1.00      1.00     88166

[[38263     0]
 [  254 49649]]


In [123]:
from xgboost import XGBClassifier
model_xgb=XGBClassifier()
model_xgb.fit(X_train,y_train)
y_train_pred=model_xgb.predict(X_train)
y_test_pred=model_xgb.predict(X_test)

In [124]:
probs=model_xgb.predict_proba(X_test)[:,1]
roc_score['xgboost']=roc_auc_score(y_test,probs)


In [125]:
report=classification_report(y_train,y_train_pred)
matrix=confusion_matrix(y_train,y_train_pred)
print(report)
print(matrix)


report=classification_report(y_test,y_test_pred)
matrix=confusion_matrix(y_test,y_test_pred)
print(report)
print(matrix)

              precision    recall  f1-score   support

         0.0       0.99      1.00      1.00    152568
         1.0       1.00      1.00      1.00    200096

    accuracy                           1.00    352664
   macro avg       1.00      1.00      1.00    352664
weighted avg       1.00      1.00      1.00    352664

[[152559      9]
 [   900 199196]]
              precision    recall  f1-score   support

         0.0       0.99      1.00      1.00     38263
         1.0       1.00      1.00      1.00     49903

    accuracy                           1.00     88166
   macro avg       1.00      1.00      1.00     88166
weighted avg       1.00      1.00      1.00     88166

[[38262     1]
 [  217 49686]]


In [126]:
# from sklearn.metrics import roc_curve
# import matplotlib.pyplot as plt

# fpr, tpr, thresholds = roc_curve(y_test, probs)


# # 4. Plot the ROC curve
# plt.figure(figsize=(8, 6))
# plt.plot(fpr, tpr, color='blue', label=f'AUC = {roc_score:.2f}')
# plt.plot([0, 1], [0, 1], linestyle='--', color='grey')  # diagonal line for reference
# plt.xlabel('False Positive Rate')
# plt.ylabel('True Positive Rate (Recall)')
# plt.title('ROC Curve')
# plt.legend(loc='lower right')
# plt.grid(True)
# plt.show()


In [127]:
new_df.head()

CustomerID   Age  Gender  Tenure  Usage Frequency  Support Calls  \
0         2.0  30.0     0.0    39.0             14.0            5.0   
1         3.0  65.0     0.0    49.0              1.0           10.0   
2         4.0  55.0     0.0    14.0              4.0            6.0   
3         5.0  58.0     1.0    38.0             21.0            7.0   
4         6.0  23.0     1.0    32.0             20.0            5.0   

   Payment Delay  Total Spend  Last Interaction  Churn  \
0           18.0        932.0              17.0    1.0   
1            8.0        557.0               6.0    1.0   
2           18.0        185.0               3.0    1.0   
3            7.0        396.0              29.0    1.0   
4            8.0        617.0              20.0    1.0   

   Contract Length_Annual  Contract Length_Monthly  Contract Length_Quarterly  \
0                     1.0                      0.0                        0.0   
1                     0.0                      1.0                        0.0   
2                     0.0                      0.0                        1.0   
3                     0.0                      1.0                        0.0   
4                     0.0                      1.0                        0.0   

   Subscription Type_Basic  Subscription Type_Premium  \
0                      0.0                        0.0   
1                      1.0                        0.0   
2                      1.0                        0.0   
3                      0.0                        0.0   
4                      1.0                        0.0   

   Subscription Type_Standard  
0                         1.0  
1                         0.0  
2                         0.0  
3                         1.0  
4                         0.0

In [128]:
from sklearn.linear_model import LogisticRegression

regressor=LogisticRegression(max_iter=1000)
regressor.fit(X_train,y_train)
y_train_pred=regressor.predict(X_train)
y_test_pred=regressor.predict(X_test)

In [129]:
probs=regressor.predict_proba(X_test)[:,1]
roc_score['logisticRegression']=roc_auc_score(y_test,probs)


In [130]:
report=classification_report(y_train,y_train_pred)
matrix=confusion_matrix(y_train,y_train_pred)
print(report)
print(matrix)


report=classification_report(y_test,y_test_pred)
matrix=confusion_matrix(y_test,y_test_pred)
print(report)
print(matrix)

              precision    recall  f1-score   support

         0.0       0.86      0.90      0.88    152568
         1.0       0.92      0.89      0.90    200096

    accuracy                           0.89    352664
   macro avg       0.89      0.89      0.89    352664
weighted avg       0.90      0.89      0.89    352664

[[138043  14525]
 [ 22973 177123]]
              precision    recall  f1-score   support

         0.0       0.86      0.90      0.88     38263
         1.0       0.92      0.89      0.90     49903

    accuracy                           0.89     88166
   macro avg       0.89      0.89      0.89     88166
weighted avg       0.89      0.89      0.89     88166

[[34557  3706]
 [ 5690 44213]]


In [131]:
from sklearn.neighbors import KNeighborsClassifier

knn=KNeighborsClassifier(n_neighbors=5,algorithm='auto',weights='uniform')
knn.fit(X_train,y_train)
y_train_pred=knn.predict(X_train)
y_test_pred=knn.predict(X_test)

In [132]:
probs=knn.predict_proba(X_test)[:,1]
roc_score['knn']=roc_auc_score(y_test,probs)


In [133]:
report=classification_report(y_train,y_train_pred)
matrix=confusion_matrix(y_train,y_train_pred)
print(report)
print(matrix)


report=classification_report(y_test,y_test_pred)
matrix=confusion_matrix(y_test,y_test_pred)
print(report)
print(matrix)

              precision    recall  f1-score   support

         0.0       0.86      0.99      0.92    152568
         1.0       0.99      0.87      0.93    200096

    accuracy                           0.92    352664
   macro avg       0.92      0.93      0.92    352664
weighted avg       0.93      0.92      0.92    352664

[[150613   1955]
 [ 25032 175064]]
              precision    recall  f1-score   support

         0.0       0.82      0.97      0.89     38263
         1.0       0.98      0.83      0.90     49903

    accuracy                           0.89     88166
   macro avg       0.90      0.90      0.89     88166
weighted avg       0.91      0.89      0.89     88166

[[37199  1064]
 [ 8360 41543]]


In [134]:
from sklearn.naive_bayes import GaussianNB

nb=GaussianNB()
nb.fit(X_train,y_train)
y_train_pred=nb.predict(X_train)
y_test_pred=nb.predict(X_test)

In [135]:
probs=nb.predict_proba(X_test)[:,1]
roc_score['naive_bayes']=roc_auc_score(y_test,probs)


In [136]:
report=classification_report(y_train,y_train_pred)
matrix=confusion_matrix(y_train,y_train_pred)
print(report)
print(matrix)


report=classification_report(y_test,y_test_pred)
matrix=confusion_matrix(y_test,y_test_pred)
print(report)
print(matrix)

              precision    recall  f1-score   support

         0.0       0.78      1.00      0.87    152568
         1.0       1.00      0.78      0.88    200096

    accuracy                           0.87    352664
   macro avg       0.89      0.89      0.87    352664
weighted avg       0.90      0.87      0.88    352664

[[152508     60]
 [ 44035 156061]]
              precision    recall  f1-score   support

         0.0       0.78      1.00      0.87     38263
         1.0       1.00      0.78      0.88     49903

    accuracy                           0.87     88166
   macro avg       0.89      0.89      0.87     88166
weighted avg       0.90      0.87      0.87     88166

[[38253    10]
 [11037 38866]]


In [137]:
from sklearn.ensemble import GradientBoostingClassifier

gb=GradientBoostingClassifier()
gb.fit(X_train,y_train)
y_train_pred=gb.predict(X_train)
y_test_pred=gb.predict(X_test)

In [138]:
probs=gb.predict_proba(X_test)[:,1]
roc_score['gradientBoosting']=roc_auc_score(y_test,probs)


In [139]:
report=classification_report(y_train,y_train_pred)
matrix=confusion_matrix(y_train,y_train_pred)
print(report)
print(matrix)


report=classification_report(y_test,y_test_pred)
matrix=confusion_matrix(y_test,y_test_pred)
print(report)
print(matrix)

              precision    recall  f1-score   support

         0.0       0.99      1.00      1.00    152568
         1.0       1.00      0.99      1.00    200096

    accuracy                           1.00    352664
   macro avg       1.00      1.00      1.00    352664
weighted avg       1.00      1.00      1.00    352664

[[152541     27]
 [  1227 198869]]
              precision    recall  f1-score   support

         0.0       0.99      1.00      1.00     38263
         1.0       1.00      0.99      1.00     49903

    accuracy                           1.00     88166
   macro avg       1.00      1.00      1.00     88166
weighted avg       1.00      1.00      1.00     88166

[[38263     0]
 [  307 49596]]


In [142]:
for i in roc_score:
    print(i,roc_score[i])

random_forest 0.9983246056270316
xgboost 0.9983620069365847
logisticRegression 0.9576911922193898
knn 0.9461257557692397
naive_bayes 0.981068074091807
gradientBoosting 0.9982246003107565


In [148]:
models={
    'random_forest':RandomForestClassifier(),
    'xgboost':XGBClassifier(),
    'logisticRegression':LogisticRegression(max_iter=1000),
    'knn':KNeighborsClassifier(n_neighbors=5,algorithm='auto',weights='uniform'),
    'naive_bayes':GaussianNB(),
    'gradientBoosting':GradientBoostingClassifier()
}


best_model_name=max(roc_score,key=roc_score.get)
for name in models:
    if name==best_model_name:
        best_model=models[name]
print(best_model_name)
print(best_model)


xgboost
XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)


In [149]:
# num_cols=['Age','Tenure','Usage Frequency','Support Calls','Payment Delay','Total Spend','Last Interaction']
# # cat_cols_onehot_encode=['Subscription Type','Contract Length']
# cat_cols_label_encode=['Gender']

In [157]:
# from sklearn.pipeline import Pipeline

# pipeline=Pipeline(
#     steps=[
#         ('preprocessor',preprocessor),
#         ('model',best_model)
#     ]
# )

In [160]:
import joblib
joblib.dump(best_model,'model.pkl')

['model.pkl']

In [161]:
joblib.dump(new_df,'preprocessed_data.pkl')

['preprocessed_data.pkl']